language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Prevent Travis's default of: mvn install -DskipTests=true
install: ""

script:
  - export MAVEN_OPTS="-Xmx2g"
  - mvn clean package
 